Performed data exploration and statistical analysis to identify the correct explanatory variables in R and plots
were visualized on the tableau. Formulated the right hypothesis on the given panel data and performed Regressions using
Fixed effects in STATA. Selected the best model by avoiding serial correlation and heteroskedasticity by using 
Cluster Robust standard errors with variables at 5 % significance level.
